[project]
name = "assignment-1"
version = "0.1.0"
description = "Assignment 1 for AU COMP 5630 (ML) Linear Regression Assignment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
]
